export const authConstant = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILED: "LOGOUT_FAILED",
}

export const signupConstant = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILED: "SIGNUP_FAILED"
}

export const categoryConstant = {
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
    ADD_CATEGORY_REQUEST:  'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS:  'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE:  'ADD_CATEGORY_FAILURE',
}

export const productConstant = {
    GET_PRODUCT_BY_SLUG_SUCCESS: ' GET_PRODUCT_BY_SLUG_SUCCESS',
    GET_PRODUCT_BY_SLUG_FAILURE: 'GET_PRODUCT_BY_SLUG_FAILURE',

    GET_PRODUCT_BY_PAGE_REQUEST: ' GET_PRODUCT_BY_PAGE_REQUEST',
    GET_PRODUCT_BY_PAGE_SUCCESS: ' GET_PRODUCT_BY_PAGE_SUCCESS',
    GET_PRODUCT_BY_PAGE_FAILURE: 'GET_PRODUCT_BY_PAGE_FAILURE',

    GET_PRODUCT_DETAILS_BY_ID_REQUEST: 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: 'GET_PRODUCT_DETAILS_BY_ID_FAILURE',

}

export const cartConstant = {
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

    REMOVE_CART_ITEM_REQUEST: 'REMOVE_CART_ITEM_REQUEST',
    REMOVE_CART_ITEM_SUCCESS: 'REMOVE_CART_ITEM_SUCCESS',
    REMOVE_CART_ITEM_FAILURE: 'REMOVE_CART_ITEM_FAILURE',
    RESET_CART: 'RESET_CART'
}

export const userConstant = {
    GET_USER_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
    GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
    GET_USER_ADDRESS_FAILURE: 'GET_USER_ADDRESS_FAILURE',

    ADD_USER_ADDRESS_REQUEST: 'ADD_USER_ADDRESS_REQUEST',
    ADD_USER_ADDRESS_SUCCESS: 'ADD_USER_ADDRESS_SUCCESS',
    ADD_USER_ADDRESS_FAILURE: 'ADD_USER_ADDRESS_FAILURE',

    GET_USER_ORDER_REQUEST: 'GET_USER_ORDER_REQUEST',
    GET_USER_ORDER_SUCCESS: 'GET_USER_ORDER_SUCCESS',
    GET_USER_ORDER_FAILURE: 'GET_USER_ORDER_FAILURE',

    ADD_USER_ORDER_REQUEST: 'ADD_USER_ORDER_REQUEST',
    ADD_USER_ORDER_SUCCESS: 'ADD_USER_ORDER_SUCCESS',
    ADD_USER_ORDER_FAILURE: 'ADD_USER_ORDER_FAILURE',

    GET_USER_ORDER_DETAILS_REQUEST: 'GET_USER_ORDER_DETAILS_REQUEST',
    GET_USER_ORDER_DETAILS_SUCCESS: 'GET_USER_ORDER_DETAILS_SUCCESS',
    GET_USER_ORDER_DETAILS_FAILURE: 'GET_USER_ORDER_DETAILS_FAILURE',
}





